apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workload-1-nginx
  template:
    metadata:
      labels:
        app: workload-1-nginx
    spec:
      containers:
        - image: public.ecr.aws/nginx/nginx
          name: nginx
